export const actionTypes = {
  RESET_STATE: "CRUD_RESET_STATE",
  CURRENT_ITEM: "CRUD_CURRENT_ITEM",
  REQUEST_LOADING: "CRUD_REQUEST_LOADING",
  REQUEST_SUCCESS: "CRUD_REQUEST_SUCCESS",
  REQUEST_FAILED: "CRUD_REQUEST_FAILED",
  CURRENT_ACTION: "CRUD_CURRENT_ACTION",
  RESET_ACTION: "CRUD_RESET_ACTION",
};
